name: Pull Requests CI

on:
    pull_request:
        branches: ['main']

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
                  cache: yarn

            - name: Install dependencies
              run: |
                  yarn install

            - name: Build documentation
              run: |
                  yarn clean
                  yarn build

            - name: Check formatting with Prettier
              run: |
                  yarn format:check

            - name: Spellcheck the documentation
              run: |
                  yarn spell
